language: python
sudo: required
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run --source='.' manage.py test joshgrid
after_success:
  coveralls
# Slack notifications
notifications:
  slack: protongroup:bCyAwaxR9YXbOggBjouCJq2d
