# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(blank=True, max_length=100)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_address', models.CharField(max_length=100)),
                ('mail_subject', models.CharField(max_length=100)),
                ('mail_body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('time_created', 'sender_name'),
            },
        ),
    ]
